import { MatchController } from "../controllers/MatchController";
import { IPmcData } from "../models/eft/common/IPmcData";
import { IGetBodyResponseData } from "../models/eft/httpResponse/IGetBodyResponseData";
import { INullResponseData } from "../models/eft/httpResponse/INullResponseData";
import { IEndOfflineRaidRequestData } from "../models/eft/match/IEndOfflineRaidRequestData";
import { IGetProfileRequestData } from "../models/eft/match/IGetProfileRequestData";
import { IStartOfflineRaidRequestData } from "../models/eft/match/IStartOffineRaidRequestData";
import { DatabaseServer } from "../servers/DatabaseServer";
import { HttpResponseUtil } from "../utils/HttpResponseUtil";
import { JsonUtil } from "../utils/JsonUtil";
export declare class MatchCallbacks {
    protected httpResponse: HttpResponseUtil;
    protected jsonUtil: JsonUtil;
    protected matchController: MatchController;
    protected databaseServer: DatabaseServer;
    constructor(httpResponse: HttpResponseUtil, jsonUtil: JsonUtil, matchController: MatchController, databaseServer: DatabaseServer);
    updatePing(url: string, info: any, sessionID: string): INullResponseData;
    exitMatch(url: string, info: any, sessionID: string): INullResponseData;
    exitToMenu(url: string, info: any, sessionID: string): INullResponseData;
    startGroupSearch(url: string, info: any, sessionID: string): INullResponseData;
    stopGroupSearch(url: string, info: any, sessionID: string): INullResponseData;
    sendGroupInvite(url: string, info: any, sessionID: string): INullResponseData;
    acceptGroupInvite(url: string, info: any, sessionID: string): INullResponseData;
    cancelGroupInvite(url: string, info: any, sessionID: string): INullResponseData;
    putMetrics(url: string, info: any, sessionID: string): INullResponseData;
    getProfile(url: string, info: IGetProfileRequestData, sessionID: string): IGetBodyResponseData<IPmcData[]>;
    serverAvailable(url: string, info: any, sessionID: string): IGetBodyResponseData<any> | IGetBodyResponseData<true>;
    joinMatch(url: string, info: any, sessionID: string): IGetBodyResponseData<any>;
    getMetrics(url: string, info: any, sessionID: string): IGetBodyResponseData<string>;
    getGroupStatus(url: string, info: any, sessionID: string): IGetBodyResponseData<any>;
    createGroup(url: string, info: any, sessionID: string): IGetBodyResponseData<any>;
    deleteGroup(url: string, info: any, sessionID: string): INullResponseData;
    startOfflineRaid(url: string, info: IStartOfflineRaidRequestData, sessionID: string): INullResponseData;
    endOfflineRaid(url: string, info: IEndOfflineRaidRequestData, sessionID: string): INullResponseData;
}
