// DO NOT EDIT!
// This file has been automatically generated by bump-plugin-version.js script
// please use "npm version" to bump a new version

namespace PTT;
internal static class PluginVersion
{
    internal const string VERSION = "6.0.0";
    internal const string FULL_VERSION = "6.0.0-rc.10";
}
